create schema latihan_level4_idstar_training_karyawan;

create table detail_karyawan(
	id bigint not null generated by default as identity,
	nik varchar(255),
	npwp varchar(255),
	created_date timestamptz,
	updated_date timestamptz,
	deleted_date timestamptz,
	primary key (id)
);

create table karyawan(
	id bigint not null generated by default as identity,
	nama varchar(255),
	dob date,
	status varchar(255),
	alamat text,
	detail_karyawan bigint not null,
	created_date timestamptz,
	updated_date timestamptz,
	deleted_date timestamptz,
	primary key (id,detail_karyawan),
	unique (id),
	foreign key (detail_karyawan) references latihan_level4_idstar_training_karyawan.detail_karyawan(id)
);

create table rekening(
	id bigint not null generated by default as identity,
	id_karyawan bigint not null,
	nama varchar(255),
	jenis varchar(255),
	rekening varchar(255),
	created_date timestamptz,
	updated_date timestamptz,
	deleted_date timestamptz,
	primary key (id, id_karyawan),
	foreign key (id_karyawan) references latihan_level4_idstar_training_karyawan.karyawan(id)
);

create table training(
	id bigint not null generated by default as identity,
	tema varchar(255),
	pengajar varchar(255),
	created_date timestamptz,
	updated_date timestamptz,
	deleted_date timestamptz,
	primary key (id)
);

create table training_karyawan(
	id bigint not null generated by default as identity,
	id_karyawan bigint not null,
	id_training bigint not null,
	tanggal timestamptz,
	primary key (id),
	foreign key (id_karyawan) references latihan_level4_idstar_training_karyawan.karyawan(id),
	foreign key (id_training) references latihan_level4_idstar_training_karyawan.training(id)
);